spring:
    jpa:
        show-sql: true
        database: mysql
        hibernate:
            ddl-auto: create-drop
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3310/survival project
        username: root
        password: Todaud13%